version: "3.8"

services:
  php_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8091:8091
    volumes:
      - ./html:/var/www/html
      - ./websocket/server:/var/www/websocket/server
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
